### ISSUE TITLE
Maximum number of data points?

### ISSUE THREAD

**Issue by dereklin** [paulo-raca/highcharts-contour#5] opened 2016-04-29 23:36 UTC
Is there a maximum number of data points?

333 data points work ok: http://jsfiddle.net/06n41zau/
But 334 doesn't: http://jsfiddle.net/865rtb6g/

**Comment by dereklin** [comment] 2016-04-29 23:48
This problem happens in Chrome.  It work in IE11.

**Comment by paulo-raca** [comment] 2016-05-18 03:54
This is really weird.
As far as I know, the problem is in Highcharts core, not on this plugin.
It seems that If there are too many data points, the ColorAxis gives up calculating the value range and just returns `{min:undefined, max:undefined}`.
I'll dig a bit further later, but in the meantime you can manually specify the `min` and `max` on the colorAxis

**Comment by historicbruno** [comment] 2016-06-01 22:51
I had a problem related to number of points, but it was fixed by setting the [turboThreshold](http://api.highcharts.com/highstock#plotOptions.series.turboThreshold) series option to 0. It seems to fix the problem on your JSFiddle, as well.

**Comment by paulo-raca** [comment] 2016-07-13 00:51
Seems like @historicbruno found the solution.
Thanks!

**Closed by paulo-raca** 2016-07-13 00:51 UTC

**Comment by paulo-raca** [comment] 2016-07-27 04:01
Turns out I can disable turboThreshold only for my series type.
It should no longer be an issue :D
